### ISSUE TITLE
Presets in dropdowns

### ISSUE THREAD

**Issue by lmaag182** [abstratt/cloudfier#45]
An existing many to one relationship does not show the actual setting once you call the edit screen. So for example, if I have a crude oil from a specified region (e.g. terra nova from europe) it doesn't necessarly show europe in the edit screen (e.g. asia pacific instead of europe in the dropdown). Instead it takes "the first one" for whatever reason.

**Comment by abstratt** [comment]
@hanmeiser182 Is that for the desktop or mobile UI?

**Comment by abstratt** [comment]
@hanmeiser182 never mind, reproduced it with the desktop bowser-based UI.

**Comment by abstratt** [comment]
@lmaag182 thanks for the report,  I am waiting for my next opportunity to work on Cloudfier to address this.

**Comment by abstratt** [comment]
@lmaag182 Apologies for taking so long to get back to you on this. The new UI based on abstratt/kirra-angular does not have this issue, in fact, it doesn't actually use a list.
