### ISSUE TITLE
Show UML Diagram in Orion enviroment

### ISSUE THREAD

**Issue by lmaag182** [abstratt/cloudfier#46]
Validating your designs by having a graphical notation (diagram) is very helpful. Currently the only way to do it is to copy the source code to eclipse and then use the graphviz addin.

**Comment by abstratt** [comment]
This one is a tricky one. Hosting one's own Graphviz rendering service may be too resource consuming, for a side feature. Google used to provide Graphviz support in their Chart API and we used to support it but [they deprecated it a while ago](https://developers.google.com/chart/image/docs/gallery/graphviz). If an alternative service is provided by a 3rd-party, I'd be happy to write support for it.

**Comment by abstratt** [comment]
Actually, after being impressed with the speed and stability of recent version of Graphviz (2.38), this is more likely to occur.

**Comment by abstratt** [comment]
@lmaag182 see also: https://groups.google.com/forum/#!topic/textuml-toolkit/-I0VEqUDeLo

**Comment by abstratt** [comment]
An initial version of the support is now available 9since 656e26a9ff3a9190967dc8e3ff0fd527b0029299). Struggling a bit to deploy the latest code to cloudfier.com, but it should be available there soon too. See write-up at: http://blog.abstratt.com/2015/06/05/showing-class-diagrams-for-your-cloudfier-apps/

**Comment by abstratt** [comment]
@lmaag182 Ok, this is now available on cloudfier.com. Please take a look and report bugs if you find any issues.

**Comment by lmaag182** [comment]
Sweet! I'll give it a try asap.

**Comment by abstratt** [comment]
@lmaag182 thanks - please mind issue #53, which should be fixed soon.
