### ISSUE TITLE
Allow singletons

### ISSUE THREAD

**Issue by lmaag182** [abstratt/cloudfier#48]
Sometimes classes do not need instantiation, e.g. in case their only purpose is to provide an operation.

**Comment by abstratt** [comment]
It is possible already to define static operations in entities, which are exposed to end users - see [Expense#newExpense](https://github.com/abstratt/cloudfier-examples/blob/master/expenses/expenses.tuml#L101) in the expenses application:

![image](https://cloud.githubusercontent.com/assets/2187522/7810889/5ec62f40-037c-11e5-8225-a5844a442f8c.png)

It is also possible to define a class which only provides static operations, but in this case they are not exposed to users (only static actions defined on entities are), but then you can define an operation in an entity that uses it.

@lmaag182 Does that fit the bill?

**Comment by abstratt** [comment]
@lmaag182 I am assuming what I describe above satisfies the original request. Please let me know otherwise.
